# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Birthday', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Confirm', models.CharField(max_length=200)),
            ],
        ),
    ]
